### ISSUE TITLE
Please do a release for pulp 3.0.0rc5 compatibility

### ISSUE THREAD

**Issue by mikedep333** [gmbnomis/pulp_cookbook#41]
Both gmbnomis and I have tested https://github.com/gmbnomis/pulp_cookbook/issues/39 with pulp 3.0.0rc5.

Please do a release so that users (and container image builders such as yours truly) can follow the usual workflow for installing pulp_cookbook (latest tag / release on PyPI) rather than installing the master branch.

**Comment by gmbnomis** [comment]
@mikedep333 I did not realize that you were waiting for it. I am still struggling to get the (old) CI setup working again, but probably it is a lost cause...

Therefore, I just released pulp-cookbook v0.1.0b1 manually. Please let me know if you encounter problems.
